version: "3.5"
services:
    selenium-hub:
        image: selenium/hub
        ports:
          -  "4444:4444"
        networks:
          -  my-network
    chrome:
        image: selenium/node-chrome
        depends_on:
          -  selenium-hub
        environment:
          -  HUB_HOST=selenium-hub
          -  HUB_PORT=4444
        volumes:
          -  /dev/shm/:/dev/shm
        networks:
          -  my-network
    firefox:
        image: selenium/node-firefox
        depends_on:
          -  selenium-hub
        environment:
          -  HUB_HOST=selenium-hub
          -  HUB_PORT=4444
        volumes:
          -  /dev/shm/:/dev/shm
        networks:
          -  my-network
    vinoth-demo-CH:
        image: vinoth/demo-site
        depends_on:
          -  chrome
          -  firefox
        environment:
          -  HUB_HOST=192.168.1.6
          -  BROWSER=Chrome
          -  MODULE=testng.xml
        volumes:
          -  ./outputCH:/vinoth/test-output
        networks:
          -  my-network      
    vinoth-demo-FF:
        image: vinoth/demo-site
        depends_on:
          -  chrome
          -  firefox
        environment:
          -  HUB_HOST=192.168.1.6
          -  BROWSER=Firefox
          -  MODULE=testng.xml
        volumes:
          -  ./outputFF:/vinoth/test-output
        networks:
          -  my-network

networks:
    my-network:
      name: grid